export const headerData =[
    {
        name:"fantasy",
        img:"./Assests/space.png"
    },
    {
        name:"Adventure",
        img:"./Assests/adventure.jpg"
    },
    {
        name:"Mystery",
        img:"./Assests/mystry.jpg"
    },
    {
        name:"Histroy",
        img:"./Assests/histroy.jpg"
    },
    {
        name:"Sports",
        img:"./Assests/sports.png"
    }
]